110/Session 4 - test/Rental/Models/Cars.cs
namespace Rental.Models
{
    public class Car
    {
        public int Id { get; set; }

        public string Make { get; set; }

        public string Model { get; set; }

        public int Year { get; set; }

        public decimal DailyPrice { get; set; }

        public int Cyls { get; set; }

        public int Passengers { get; set; }


        // 0 - economy, 1 - mid lux, 2 - lux, 3 - sport, 4 - super sport
        public int Type { get; set; }

        public string ImageURL { get; set; }

        public string Description { get; set; }

        public string FuelType { get; set; }

    }
}

110/Session 4 - test/Rental/Controllers/CatalogController.cs
using Microsoft.AspNetCore.Mvc;
using Rental.Models;
using System.Collections.Generic;
using System.Linq;

namespace Rental.Controllers
{
    public class CatalogController : Controller
    {
        private DataContext dbContext;
        public CatalogController(DataContext context)
        {
            this.dbContext = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SaveCar([FromBody] Car theCar){
            dbContext.Cars.Add(theCar);
            dbContext.SaveChanges();
            return Json(theCar);
        }
        [HttpGet]
        public IActionResult GetCatalog()
        {
            // Car c1 = new Car();
            // c1.Make = "Dodge";
            // c1.Model = "Charger";
            // c1.Year = 2014;
            // c1.Cyls = 8;
            // c1.Description = "Hellcat, 'nuff said";
            // c1.DailyPrice = 132m;
            // c1.ImageURL = "https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fst.motortrend.com%2Fuploads%2Fsites%2F5%2F2014%2F12%2F2015-Dodge-Charger-SRT-Hellcat-front-three-quarter-view-in-motion-13.jpg&f=1&nofb=1";

            // Car c2 = new Car();
            // c2.Make = "Dodge";
            // c2.Model = "Durango";
            // c2.Year = 2018;
            // c2.Cyls = 8;
            // c2.Description = "SRT, carry your family in style";
            // c2.DailyPrice = 74m;
            // c2.ImageURL = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.PZB6p0CObQBW03oKlejLfAHaE8%26pid%3DApi&f=1";

            // List<Car> list = new List<Car>();
            // list.Add(c1);
            // list.Add(c2);

            var list = dbContext.Cars.ToList();
            return Json(list);
        }
    }
}

110/Session 4 - test/Rental/Views/Catalog/Register.cshtml
@{
    ViewData["title"] = "Register Car";
}

<h1>Register new car here</h1>

<div class="form">
   <div class="form-group row">
        <label class="col-4 form-group-label" for="year">Year:</label>
        <div class="col-8">
            <input type="text" class="form-control" placeholder="2019"/>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-4 form-group-label" for="make">Make:</label>
        <div class="col-8">
            <input type="text" class="form-control" placeholder="Dodge"/>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-4 form-group-label" for="model">Model:</label>
        <div class="col-8">
            <input type="text" class="form-control" placeholder="Charger"/>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-4 form-group-label" for="cyls">Cylinders:</label>
        <div class="col-8">
            <input type="text" class="form-control" placeholder="4"/>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-4 form-group-label" for="dailyPrice">Daily Price:</label>
        <div class="col-8">
            <input type="text" class="form-control" placeholder="24.99"/>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-4 form-group-label" for="imageUrl">Image Link:</label>
        <div class="col-8">
            <input type="text" class="form-control" placeholder=""/>
        </div>
    </div>
</div>

@section Styles{
    <link rel="stylesheet" href="/css/register.css">
}

110/Session 4 - test/Rental/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rental</title>
    <link rel="icon" href="/img/Smiley-cool-icon.png"/>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Rental</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
             <ul class="navbar-nav flex-grow-1">
                 <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                 </li>
                  <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Catalog" asp-action="Index">Catalog</a>
                 </li>
                 <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Catalog" asp-action="Register">Register Car</a>
                 </li>
                 <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About me</a>
                 </li>
               
                 </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Rental - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>